
# This file tells Netlify how to build and deploy your app

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  
  # Default build command
  command = "npm run build"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
